DATABASE_USERNAME = 'postgres'
DATABASE_PWD = 'postgres'
DATABASE_HOST = 'localhost'
DATABASE_PORT = 5432
DATABASE_NAME = 'patients'

DATABASE_URL = f'postgresql://{DATABASE_USERNAME}:{DATABASE_PWD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}'