"""thirdState

Revision ID: 354bfed247c0
Revises: 7e064c9b0300
Create Date: 2025-05-10 16:27:44.961194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '354bfed247c0'
down_revision: Union[str, None] = '7e064c9b0300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patientinfo', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patientinfo', 'priority')
    # ### end Alembic commands ###
