"""secondState

Revision ID: 7e064c9b0300
Revises: 537e4241f3e4
Create Date: 2025-05-10 16:25:06.137922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e064c9b0300'
down_revision: Union[str, None] = '537e4241f3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patientinfo', sa.Column('content', sa.String(length=1000), nullable=False))
    op.add_column('patientinfo', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('patientinfo', 'info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patientinfo', sa.Column('info', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.drop_column('patientinfo', 'date')
    op.drop_column('patientinfo', 'content')
    # ### end Alembic commands ###
